# SPDX-License-Identifier: Apache-2.0

name: 'Update constraints file'
description: 'Updates constraints file from requirements'
author: 'InstructLab'
inputs:
  gh-token:
    required: true
    description: >-
      GitHub token to use for authentication.

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: '3.11'

    - name: Install tox
      shell: bash
      run: python -m pip install --upgrade pip tox -c constraints-dev.txt

    - name: Run tox constraints
      shell: bash
      run: tox -e constraints -- ${{ github.action_path }}/generate_constraints.sh

    - name: git diff
      shell: bash
      run: |
        git diff constraints-dev.txt

    - name: set release date
      shell: bash
      run: |
        echo "date=$(date --rfc-3339=date)" >> "${GITHUB_ENV}"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
      with:
        add-paths: constraints-dev.txt
        signoff: true
        commit-message: "chore: update constraints-dev.txt (${{ env.date }})"
        title: "chore: update constraints-dev.txt (${{ env.date }})"
        body: |
          This PR updates the constraints-dev.txt file using `tox -e constraints`.
        branch: update-constraints
        token: ${{ inputs.gh-token }}
